services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db

  backend:
    image: ankitks001/dd-mean-backend:1.0
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo:27017/dd_db
    depends_on:
      - mongo

  frontend:
    image: ankitks001/dd-mean-frontend:1.0
    container_name: frontend
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  mongo-data: